#!/bin/sh

DT=`env TZ=America/Detroit date`
LN=`env TZ=Europe/London date`
NY=`env TZ=America/New_York date`
CA=`env TZ=America/California date`

echo "Detroit        $DT"
echo "London         $LN"
echo "New York       $NY"
echo "California     $CA"

PT=`env TZ=US/Pacific date`
CT=`env TZ=US/Central date`
AT=`env TZ=Australia/Melbourne date`


#echo "Santa Clara    $PT"
#echo "Central        $CT"
#echo "Melbourne      $AT"
